### PR TITLE
Convert duration to days for past indices calculation

### LINKED ISSUE #1038: Error when defining `unit_investment_lifetime`
**Describe the bug**
When defining the parameter `unit_investment_lifetime` with a value SpineOpt breaks in the attached example.

[data.json](https://github.com/user-attachments/files/16030992/data.json)

Note: if you use `none` (default value) then the model runs correctly

Te problem seems to arrise when building the `constraint_unit_lifetime`.

@manuelma Any idea to fix this?

**To Reproduce**
Please use the attached json file to reproduce the error.

**Expected behavior**
To doesn't break

**Desktop (please complete the following information):**
- Which SpineOpt version? latest master
- Which toolbox version? latest master
- OS: Windows

**Additional context**
Here is the log of the problem:

```log
[SpineOpt version 0.8.2 (git hash: b727a95e95600fae6f6c1ae54d67cfd48bb52da8)]
[SpineInterface version 0.14.4 (git hash: b35b35371e89e1f385c79a49ca23d1727cc990cf)]
Execution started at 2024-06-28T14:17:23.52
Reading input data from sqlite:///C:\Users\wangn\OneDrive - TNO\MOPO\SpineToolbox-Projects\Tutorials\Simple investment\.spinetoolbox\items\input\input.sqlite...
Initializing base data structure from db...  0.428040 seconds (109.33 k allocations: 10.190 MiB, 6.17% compilation time)
Preprocessing base data structure...  0.042723 seconds (16.39 k allocations: 1.158 MiB, 26.31% compilation time)
Checking base data structure...  0.006108 seconds (1.80 k allocations: 127.891 KiB, 94.37% compilation time)
Creating simple temporal structure...  0.233114 seconds (386.93 k allocations: 24.924 MiB, 20.10% gc time, 92.75% compilation time)
Creating simple stochastic structure...  0.011198 seconds (5.65 k allocations: 772.883 KiB, 55.28% compilation time)
Adding simple variables...
- [variable_binary_gas_connection_flow]  0.000352 seconds (2.08 k allocations: 47.672 KiB)
- [variable_connection_flow]  0.000186 seconds (2.03 k allocations: 42.625 KiB)
- [variable_connection_intact_flow]  0.000225 seconds (2.03 k allocations: 42.344 KiB)
- [variable_connections_decommissioned]  0.000215 seconds (2.06 k allocations: 43.078 KiB)
- [variable_connections_invested]  0.000202 seconds (2.07 k allocations: 43.281 KiB)
- [variable_connections_invested_available]  0.000231 seconds (2.07 k allocations: 43.344 KiB)
- [variable_min_capacity_margin_slack]  0.000207 seconds (2.04 k allocations: 42.438 KiB)
- [variable_node_injection]  0.000349 seconds (2.50 k allocations: 92.070 KiB)
- [variable_node_pressure]  0.000213 seconds (2.04 k allocations: 42.766 KiB)
- [variable_node_slack_neg]  0.000144 seconds (2.03 k allocations: 42.344 KiB)
- [variable_node_slack_pos]  0.000187 seconds (2.04 k allocations: 44.844 KiB)
- [variable_node_state]  0.000171 seconds (2.06 k allocations: 43.109 KiB)
- [variable_node_voltage_angle]  0.000204 seconds (2.04 k allocations: 42.719 KiB)
- [variable_nonspin_units_shut_down]  0.000204 seconds (2.08 k allocations: 44.516 KiB)
- [variable_nonspin_units_started_up]  0.000203 seconds (2.08 k allocations: 44.438 KiB)
- [variable_storages_decommissioned]  0.000182 seconds (2.06 k allocations: 43.203 KiB)
- [variable_storages_invested]  0.000160 seconds (2.07 k allocations: 43.594 KiB)
- [variable_storages_invested_available]  0.000145 seconds (2.07 k allocations: 43.719 KiB)
- [variable_unit_flow]  0.087164 seconds (17.23 k allocations: 1.178 MiB, 98.40% compilation time)
- [variable_unit_flow_op]  0.000404 seconds (2.07 k allocations: 45.375 KiB)
- [variable_unit_flow_op_active]  0.000253 seconds (2.07 k allocations: 45.797 KiB)
- [variable_units_invested]  0.120676 seconds (149.09 k allocations: 11.570 MiB, 96.31% compilation time)
- [variable_units_invested_available]  0.106720 seconds (175.35 k allocations: 13.784 MiB, 92.13% compilation time)
- [variable_units_mothballed]  0.000417 seconds (2.80 k allocations: 117.750 KiB)
- [variable_units_on]  0.000378 seconds (2.61 k allocations: 97.945 KiB)
- [variable_units_out_of_service]  0.000264 seconds (2.05 k allocations: 43.609 KiB)
- [variable_units_returned_to_service]  0.000204 seconds (2.04 k allocations: 43.156 KiB)
- [variable_units_shut_down]  0.000198 seconds (2.05 k allocations: 43.406 KiB)
- [variable_units_started_up]  0.000164 seconds (2.05 k allocations: 43.406 KiB)
- [variable_units_taken_out_of_service]  0.000226 seconds (2.04 k allocations: 43.266 KiB)
- [variable_user_constraint_slack_neg]  0.000182 seconds (1.99 k allocations: 40.281 KiB)
- [variable_user_constraint_slack_pos]  0.000156 seconds (1.99 k allocations: 40.281 KiB)
  0.324849 seconds (404.89 k allocations: 28.062 MiB, 92.45% compilation time)
Adding simple expressions...
- [expression_capacity_margin]  0.000030 seconds (14 allocations: 1.562 KiB)
  0.000147 seconds (70 allocations: 5.062 KiB)
Adding simple constraints...
- [constraint_candidate_connection_flow_lb]  0.000014 seconds (15 allocations: 880 bytes)
- [constraint_candidate_connection_flow_ub]  0.000011 seconds (15 allocations: 880 bytes)
- [constraint_compression_ratio]  0.000027 seconds (20 allocations: 1.750 KiB)
- [constraint_connection_flow_capacity]  0.000051 seconds (42 allocations: 3.141 KiB)
- [constraint_connection_flow_gas_capacity]  0.000019 seconds (20 allocations: 1.750 KiB)
- [constraint_connection_flow_intact_flow]  0.000011 seconds (15 allocations: 880 bytes)
- [constraint_connection_flow_lodf]  0.000064 seconds (58 allocations: 3.875 KiB)
- [constraint_connection_intact_flow_capacity]  0.000011 seconds (15 allocations: 880 bytes)
- [constraint_connection_intact_flow_ptdf]  0.000029 seconds (24 allocations: 1.859 KiB)
- [constraint_connection_lifetime]  0.000055 seconds (49 allocations: 3.062 KiB)
- [constraint_connection_unitary_gas_flow]  0.000014 seconds (20 allocations: 1.750 KiB)
- [constraint_connections_invested_available]  0.000052 seconds (53 allocations: 2.953 KiB)
- [constraint_connections_invested_transition]  0.000036 seconds (26 allocations: 1.906 KiB)
- [constraint_cyclic_node_state]  0.006148 seconds (1.38 k allocations: 98.203 KiB, 97.88% compilation time)
- [constraint_fix_node_pressure_point]  0.000025 seconds (23 allocations: 3.000 KiB)
- [constraint_fix_ratio_in_in_unit_flow]  0.000114 seconds (121 allocations: 27.172 KiB)
- [constraint_fix_ratio_in_out_unit_flow]  0.000049 seconds (121 allocations: 27.172 KiB)
- [constraint_fix_ratio_out_in_connection_flow]  0.000028 seconds (23 allocations: 1.906 KiB)
- [constraint_fix_ratio_out_in_unit_flow]  0.000057 seconds (121 allocations: 27.172 KiB)
- [constraint_fix_ratio_out_out_unit_flow]  0.000055 seconds (121 allocations: 27.172 KiB)
- [constraint_investment_group_equal_investments]  0.000036 seconds (23 allocations: 1.828 KiB)
- [constraint_investment_group_maximum_capacity_invested_available]  0.000019 seconds (21 allocations: 1.797 KiB)
- [constraint_investment_group_maximum_entities_invested_available]  0.000018 seconds (21 allocations: 1.797 KiB)
- [constraint_investment_group_minimum_capacity_invested_available]  0.000019 seconds (20 allocations: 1.750 KiB)
- [constraint_investment_group_minimum_entities_invested_available]  0.000018 seconds (20 allocations: 1.750 KiB)
- [constraint_max_node_pressure]  0.000102 seconds (60 allocations: 4.031 KiB)
- [constraint_max_node_voltage_angle]  0.000047 seconds (62 allocations: 4.125 KiB)
- [constraint_max_ratio_in_in_unit_flow]  0.000059 seconds (121 allocations: 27.172 KiB)
- [constraint_max_ratio_in_out_unit_flow]  0.000056 seconds (121 allocations: 27.172 KiB)
- [constraint_max_ratio_out_in_connection_flow]  0.000022 seconds (23 allocations: 1.906 KiB)
- [constraint_max_ratio_out_in_unit_flow]  0.000050 seconds (121 allocations: 27.172 KiB)
- [constraint_max_ratio_out_out_unit_flow]  0.000064 seconds (121 allocations: 27.172 KiB)
- [constraint_max_total_cumulated_unit_flow_from_node]  0.000024 seconds (22 allocations: 1.859 KiB)
- [constraint_max_total_cumulated_unit_flow_to_node]  0.000019 seconds (24 allocations: 2.047 KiB)
- [constraint_min_capacity_margin]  0.000023 seconds (21 allocations: 1.812 KiB)
- [constraint_min_down_time]  0.000024 seconds (22 allocations: 1.859 KiB)
- [constraint_min_node_pressure]  0.000042 seconds (60 allocations: 4.031 KiB)
- [constraint_min_node_voltage_angle]  0.000041 seconds (62 allocations: 4.125 KiB)
- [constraint_min_ratio_in_in_unit_flow]  0.000050 seconds (121 allocations: 27.172 KiB)
- [constraint_min_ratio_in_out_unit_flow]  0.000044 seconds (121 allocations: 27.172 KiB)
- [constraint_min_ratio_out_in_connection_flow]  0.000016 seconds (23 allocations: 1.906 KiB)
- [constraint_min_ratio_out_in_unit_flow]  0.000044 seconds (121 allocations: 27.172 KiB)
- [constraint_min_ratio_out_out_unit_flow]  0.000073 seconds (121 allocations: 27.172 KiB)
- [constraint_min_scheduled_outage_duration]  0.000021 seconds (21 allocations: 1.812 KiB)
- [constraint_min_total_cumulated_unit_flow_from_node]  0.000016 seconds (22 allocations: 1.859 KiB)
- [constraint_min_total_cumulated_unit_flow_to_node]  0.000016 seconds (24 allocations: 2.047 KiB)
- [constraint_min_up_time]  0.000024 seconds (26 allocations: 6.484 KiB)
- [constraint_minimum_operating_point]  0.000024 seconds (23 allocations: 1.984 KiB)
- [constraint_nodal_balance]  0.005316 seconds (1.64 k allocations: 130.320 KiB, 92.59% compilation time)
- [constraint_node_injection]  0.009819 seconds (2.31 k allocations: 183.156 KiB, 91.47% compilation time)
- [constraint_node_state_capacity]  0.000079 seconds (64 allocations: 3.953 KiB)
- [constraint_node_voltage_angle]  0.000021 seconds (21 allocations: 1.797 KiB)
- [constraint_non_spinning_reserves_lower_bound]  0.000060 seconds (45 allocations: 4.016 KiB)
- [constraint_non_spinning_reserves_shut_down_upper_bound]  0.000060 seconds (54 allocations: 4.906 KiB)
- [constraint_non_spinning_reserves_start_up_upper_bound]  0.000046 seconds (54 allocations: 4.906 KiB)
- [constraint_operating_point_bounds]  0.000147 seconds (61 allocations: 4.578 KiB)
- [constraint_operating_point_rank]  0.000098 seconds (59 allocations: 4.484 KiB)
- [constraint_ramp_down]  0.000025 seconds (30 allocations: 2.453 KiB)
- [constraint_ramp_up]  0.000022 seconds (30 allocations: 2.453 KiB)
- [constraint_ratio_out_in_connection_intact_flow]  0.000013 seconds (15 allocations: 880 bytes)
- [constraint_storage_lifetime]  0.000045 seconds (49 allocations: 3.062 KiB)
- [constraint_storage_line_pack]  0.000020 seconds (21 allocations: 1.797 KiB)
- [constraint_storages_invested_available]  0.000045 seconds (54 allocations: 3.016 KiB)
- [constraint_storages_invested_transition]  0.000100 seconds (93 allocations: 5.672 KiB)
- [constraint_unit_flow_capacity]  0.001014 seconds (2.42 k allocations: 249.359 KiB)
- [constraint_unit_flow_op_bounds]  0.000090 seconds (144 allocations: 11.125 KiB)
- [constraint_unit_flow_op_rank]  0.000064 seconds (122 allocations: 9.906 KiB)
- [constraint_unit_flow_op_sum]  0.000018 seconds (23 allocations: 1.984 KiB)
ERROR: LoadError: TaskFailedException

    nested task error: MethodError: no method matching isless(::Dates.Millisecond, ::Dates.Year)

    Closest candidates are:
      isless(::Union{Dates.Day, Dates.Hour, Dates.Microsecond, Dates.Millisecond, Dates.Minute, Dates.Nanosecond, Dates.Second, Dates.Week}, ::Union{Dates.Month, Dates.Quarter, Dates.Year})
       @ Dates C:\Users\wangn\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Dates\src\periods.jl:438
      isless(::Dates.Period, ::Dates.Period)
       @ Dates C:\Users\wangn\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Dates\src\periods.jl:97
      isless(::SpineInterface.Call, ::Any)
       @ SpineInterface C:\Users\wangn\OneDrive - TNO\Repositories\SpineInterface.jl\src\base.jl:47
      ...

    Stacktrace:
      [1] isless(x::Dates.Millisecond, y::Dates.Year)
        @ Dates C:\Users\wangn\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Dates\src\periods.jl:438
      [2] <(x::Dates.Millisecond, y::Dates.Year)
        @ Base .\operators.jl:352
      [3] (::SpineOpt.var"#1141#1143"{@Kwargs{unit::SpineInterface.Object}, JuMP.Model, SpineInterface.Parameter, SpineInterface.TimeSlice})(ind::@NamedTuple{unit::SpineInterface.Object, stochastic_scenario::SpineInterface.Object, t::SpineInterface.TimeSlice})
        @ SpineOpt .\none:0
      [4] iterate
        @ .\generator.jl:47 [inlined]
      [5] macro expansion
        @ C:\Users\wangn\.julia\packages\MutableArithmetics\iovKe\src\rewrite.jl:325 [inlined]
      [6] macro expansion
        @ C:\Users\wangn\.julia\packages\JuMP\Gwn88\src\macros.jl:257 [inlined]
      [7] macro expansion
        @ C:\Users\wangn\.julia\packages\JuMP\Gwn88\src\macros\@constraint.jl:213 [inlined]
      [8] _build_constraint_unit_lifetime(m::JuMP.Model, u::SpineInterface.Object, s_path::Vector{SpineInterface.Object}, t::SpineInterface.TimeSlice)
        @ SpineOpt C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\constraints\constraint_unit_lifetime.jl:31
      [9] macro expansion
        @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\constraints\constraint_common.jl:25 [inlined]
     [10] (::SpineOpt.var"#1764#threadsfor_fun#1127"{SpineOpt.var"#1764#threadsfor_fun#1126#1128"{JuMP.Model, typeof(SpineOpt._build_constraint_unit_lifetime), Vector{Any}, Vector{@NamedTuple{unit::SpineInterface.Object, stochastic_path::Vector{SpineInterface.Object}, t::SpineInterface.TimeSlice}}, Base.OneTo{Int64}}})(tid::Int64; onethread::Bool)
        @ SpineOpt .\threadingconstructs.jl:215
     [11] #1764#threadsfor_fun
        @ .\threadingconstructs.jl:182 [inlined]
     [12] (::Base.Threads.var"#1#2"{SpineOpt.var"#1764#threadsfor_fun#1127"{SpineOpt.var"#1764#threadsfor_fun#1126#1128"{JuMP.Model, typeof(SpineOpt._build_constraint_unit_lifetime), Vector{Any}, Vector{@NamedTuple{unit::SpineInterface.Object, stochastic_path::Vector{SpineInterface.Object}, t::SpineInterface.TimeSlice}}, Base.OneTo{Int64}}}, Int64})()
        @ Base.Threads .\threadingconstructs.jl:154
Stacktrace:
  [1] threading_run(fun::SpineOpt.var"#1764#threadsfor_fun#1127"{SpineOpt.var"#1764#threadsfor_fun#1126#1128"{JuMP.Model, typeof(SpineOpt._build_constraint_unit_lifetime), Vector{Any}, Vector{@NamedTuple{unit::SpineInterface.Object, stochastic_path::Vector{SpineInterface.Object}, t::SpineInterface.TimeSlice}}, Base.OneTo{Int64}}}, static::Bool)
    @ Base.Threads .\threadingconstructs.jl:172
  [2] macro expansion
    @ .\threadingconstructs.jl:220 [inlined]
  [3] _add_constraint!(m::JuMP.Model, name::Symbol, indices::typeof(SpineOpt.constraint_unit_lifetime_indices), build_constraint::Function)
    @ SpineOpt C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\constraints\constraint_common.jl:23
  [4] add_constraint_unit_lifetime!(m::JuMP.Model)
    @ SpineOpt C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\constraints\constraint_unit_lifetime.jl:26
  [5] macro expansion
    @ .\timing.jl:279 [inlined]
  [6] macro expansion
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\util\misc.jl:51 [inlined]
  [7] _add_constraints!(m::JuMP.Model; log_level::Int64)
    @ SpineOpt C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt_basic.jl:241
  [8] _add_constraints!
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt_basic.jl:160 [inlined]
  [9] macro expansion
    @ .\timing.jl:279 [inlined]
 [10] macro expansion
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\util\misc.jl:51 [inlined]
 [11] build_model!(m::JuMP.Model; log_level::Int64)
    @ SpineOpt C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt_basic.jl:75
 [12] build_model!
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt_basic.jl:66 [inlined]
 [13] do_run_spineopt!(m::JuMP.Model, url_out::String, ::Val{:basic_algorithm}; log_level::Int64, optimize::Bool, update_names::Bool, alternative::String, write_as_roll::Int64, resume_file_path::Nothing)
    @ SpineOpt C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt_basic.jl:31
 [14] #invokelatest#2
    @ .\essentials.jl:894 [inlined]
 [15] invokelatest
    @ .\essentials.jl:889 [inlined]
 [16] run_spineopt!(m::JuMP.Model, url_out::String; log_level::Int64, optimize::Bool, update_names::Bool, alternative::String, write_as_roll::Int64, resume_file_path::Nothing)
    @ SpineOpt C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt.jl:311
 [17] run_spineopt!
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt.jl:300 [inlined]
 [18] _run_spineopt(f::SpineOpt.var"#65#66", url_in::String, url_out::String; upgrade::Bool, filters::Dict{String, String}, templates::Tuple{}, mip_solver::Nothing, lp_solver::Nothing, use_direct_model::Bool, log_level::Int64, alternative::String, kwargs::@Kwargs{optimize::Bool, update_names::Bool, write_as_roll::Int64, resume_file_path::Nothing})
    @ SpineOpt C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt.jl:142
 [19] _run_spineopt
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt.jl:119 [inlined]
 [20] #68
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt.jl:99 [inlined]
 [21] _log_to_file
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\util\misc.jl:225 [inlined]
 [22] #run_spineopt#67
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt.jl:98 [inlined]
 [23] run_spineopt
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt.jl:80 [inlined]
 [24] #run_spineopt#64
    @ C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt.jl:64 [inlined]
 [25] run_spineopt(url_in::String, url_out::String)
    @ SpineOpt C:\Users\wangn\OneDrive - TNO\Repositories\SpineOpt.jl\src\run_spineopt.jl:63
 [26] top-level scope
    @ C:\Users\wangn\.spinetoolbox\work\run_spineopt__bb7209599283493db3de2aa737f436aa__toolbox\run_spineopt.jl:3
 [27] include(fname::String)
    @ Base.MainInclude .\client.jl:489
 [28] top-level scope
    @ none:1
in expression starting at C:\Users\wangn\.spinetoolbox\work\run_spineopt__bb7209599283493db3de2aa737f436aa__toolbox\run_spineopt.jl:3
```

### PR DESCRIPTION
**Pull request by datejada**
## Motivation

Months and Years are challenging for detailed comparisons in the package Dates, since they don't have an exact length as the number of days varies in both. E.g. every leap year is longer than 365 days, so Dates doesn't allow direct comparisons with ill-defined durations as a precaution.

## Description of changes

These changes take the parameter and convert it into days if it is defined as a duration in years or months. It will use a standard value of 365 and 30 days for each one.

Fixes #1038 

## Checklist before merging
- [x] Documentation is up-to-date
- [x] Unit tests have been added/updated accordingly
- [x] Code has been formatted according to SpineOpt's style
- [x] Unit tests pass

### CODE REVIEW

File: src/constraints/constraint_common.jl [hunk 1]
```diff
@@ -70,11 +70,22 @@ past_units_on_indices(m, param, u, s_path, t) = _past_indices(m, units_on_indice
...
+    function convert_to_days(duration)
+        if isa(duration, Year)
+            return Day(Dates.value(duration) * 365)  # approximate conversion
+        elseif isa(duration, Month)
+            return Day(Dates.value(duration) * 30)   # approximate conversion
+        else
+            return duration                          # do nothing
+        end
+    end
+
```
Comment (manuelma) [inline src/constraints/constraint_common.jl:83]: Nice work @datejada - a few comments.
- I think you might run into the same issues with connection and storage lifetimes, so probably you will also need to call this function there as well.
- The other thing is just style, in Julia you have multiple dispatch which allows you to avoid those if else blocks to switch the variable type. You may have seen it, it looks something like this:
```
convert_to_days(duration::Year) = Day(Dates.value(duration) * 365)
convert_to_days(duration::Month) = Day(Dates.value(duration) * 30)
convert_to_days(duration) = duration
```
You may want to try it instead, it's faster too although it doesn't look like this code is performance-critical.
- You have chosen 365 and 30 as the multipliers which are the median but I wonder if you need to take something else instead, like the mean or the maximum. We are using the result to call isless, so si the result of isless correct in all cases?
- Unit-tests?

Comment (datejada) [reply src/constraints/constraint_common.jl:77]: Hi @manuelma 

Thank you for your comments; they are constructive 😄 So:

The new function is inside the `_past_indices` function, which is the same one used for connections and storage. So, we will catch all the cases here.
- Awesome, I will change it like this 😉 it looks more Julia.
- Good point! So, the best approximation to cover the cases will be taking the maximum since we look behind the lifetime in the index t that is in the `isless`, meaning that overestimating (i.e., 366 and 31) will guarantee to cover the lifetime to determine the `weight` value.
- I don't think we need extra tests for now since the new economic parameters branch #909 will test this situation (and hopefully, after the latest changes, it will pass the tests and can be merged soon)
